package_name: model

# LOCAL DATA FILES
raw_data: train
processed_data: processed_data
train_data_file: None
test_data_file: None
process_log_file: process.log


##################### PREPROCESSING VARIABLE SPECIFICATIONS


############ VARIABLES BY AGG. LEVEL AND DATA TYPE
identifiers:
  - 'id'
  - 'idhogar'

individual_level_binary_vars:
  - estadocivil1'
  - 'estadocivil2'
  - 'estadocivil3' 
  - 'estadocivil4'
  - 'estadocivil5' 
  - 'estadocivil6' 
  - 'estadocivil7' 
  - 'instlevel1'
  - 'instlevel2' 
  - 'instlevel3' 
  - 'instlevel4' 
  - 'instlevel5' 
  - 'instlevel6'
  - 'instlevel7' 
  - 'instlevel8' 
  - 'instlevel9' 
  - 'parentesco1'
  - 'parentesco2' 
  - 'parentesco3'
  - 'parentesco4' 
  - 'parentesco5' 
  - 'parentesco6' 
  - 'parentesco7' 
  - 'parentesco8'
  - 'parentesco9' 
  - 'parentesco10' 
  - 'parentesco11'
  - 'parentesco12' 
  - 'male'
  - 'female' 
  - 'v18q'
  - 'dis' 
  - 'mobilephone'

individual_level_ordinal:
  - 'age'
  - 'escolari'
  - 'rez_esc'


household_level_binary_vars: 
  - 'hacdor'
  - 'hacapo' 
  - 'v14a'
  - 'refrig' 
  - 'paredblolad' 
  - 'paredzocalo' 
  - 'paredpreb'
  - 'pisocemento' 
  - 'pareddes' 
  - 'paredmad'
  - 'paredzinc' 
  - 'paredfibras'
  - 'paredother' 
  - 'pisomoscer'
  - 'pisoother'
  - 'pisonatur'
  - 'pisonotiene' 
  - 'pisomadera'
  - 'techozinc' 
  - 'techoentrepiso' 
  - 'techocane'
  - 'techootro' 
  - 'cielorazo' 
  - 'abastaguadentro' 
  - 'abastaguafuera' 
  - 'abastaguano'
  - 'public'
  - 'planpri'
  - 'noelec' 
  - 'coopele'
  - 'sanitario1' 
  - 'sanitario2'
  - 'sanitario3' 
  - 'sanitario5'
  - 'sanitario6'
  - 'energcocinar1' 
  - 'energcocinar2' 
  - 'energcocinar3' 
  - 'energcocinar4' 
  - 'elimbasu1'
  - 'elimbasu2' 
  - 'elimbasu3' 
  - 'elimbasu4' 
  - 'elimbasu5' 
  - 'elimbasu6'
  - 'epared1'
  - 'epared2'
  - 'epared3'
  - 'etecho1'
  - 'etecho2'
  - 'etecho3' 
  - 'eviv1'
  - 'eviv2' 
  - 'eviv3' 
  - 'tipovivi1'
  - 'tipovivi2' 
  - 'tipovivi3' 
  - 'tipovivi4'
  - 'tipovivi5' 
  - 'computer'
  - 'television'
  - 'lugar1'
  - 'lugar2' 
  - 'lugar3'
  - 'lugar4'
  - 'lugar5' 
  - 'lugar6' 
  - 'area1'
  - 'area2'

household_level_ordinal_vars:
  - 'rooms'
  - 'r4h1'
  - 'r4h2' 
  - 'r4h3' 
  - 'r4m1'
  - 'r4m2'
  - 'r4m3' 
  - 'r4t1' 
  - 'r4t2' 
  - 'r4t3'
  - 'v18q1' 
  - 'tamhog'
  - 'tamviv'
  - 'hhsize'
  - 'hogar_nin'
  - 'hogar_adul'
  - 'hogar_mayor'
  - 'hogar_total' 
  - 'bedrooms'
  - 'qmobilephone'

household_level_continous_vars: 
  - 'v2a1'
  - 'dependency' 
  - 'edjefe'
  - 'edjefa' 
  - 'meaneduc' 
  - 'overcrowding'



############ VARIABLES BY PREPROCESSING STEPS

head_of_household_exist:
  - 'idhogar'
  - 'parentesco1'

intra_household_target_correction:
  - 'target'
  - 'idhogar'

yes_no_map_to_numerical:
  - 'edjefe'
  - 'edjefa'
  - 'dependency'

num_tablets_missing:
  - v18q
  - v18q1

rent_payment_missing:
  - v2a1
  - tipovivi1

years_behind_in_school:
  - age
  - rez_esc

redundant_squared_variables:
  - sqbescolari
  - sqbage
  - sqbhogar_total
  - sqbedjefe
  - sqbhogar_nin
  - sqbovercrowding
  - sqbdependency
  - sqbmeaned

highly_corr_vars_drop:
  - tamhog
  - hogar_total
  - r4t3

############ VARIABLES BY PREPROCESSING STEPS

electricity_variables:
  - noelec
  - coopele
  - public
  - planpri



##################### MODELLING VARIABLE SPECIFICATIONS
primary_dependent_variables:
  - target

variables_to_include:
  - var_1
  - var_2
  - var_3
  - var_4

# PARAMETER SETTINGS
random_state: 42
test_size: 0.1
alpha: 0.05
variance_threshold: 0.01